# ETL Pipeline Preparation
Follow the instructions below to help you create your ETL pipeline.
### 1. Import libraries and load datasets.
- Import Python libraries
- Load `messages.csv` into a dataframe and inspect the first few lines.
- Load `categories.csv` into a dataframe and inspect the first few lines.

In [1]:
# import libraries
import pandas as pd
from sqlalchemy import create_engine

In [2]:
# load messages dataset
messages = pd.read_csv('messages.csv')
messages.head()

,id,message,original,genre
0,2,Weather update - a cold front from Cuba that c...,Un front froid se retrouve sur Cuba ce matin. ...,direct
1,7,Is the Hurricane over or is it not over,Cyclone nan fini osinon li pa fini,direct
2,8,Looking for someone but no name,"Patnm, di Maryani relem pou li banm nouvel li ...",direct
3,9,UN reports Leogane 80-90 destroyed. Only Hospi...,UN reports Leogane 80-90 destroyed. Only Hospi...,direct
4,12,"says: west side of Haiti, rest of the country ...",facade ouest d Haiti et le reste du pays aujou...,direct

In [3]:
#number of rows and columns of messages dataset
print('Messages dataset has', messages.shape[0],'rows/message and', messages.shape[1], 'columns/features')

Messages dataset has 26248 rows/message and 4 columns/features

In [4]:
# load categories dataset
categories = pd.read_csv('categories.csv')
categories.head(30)

    id                                         categories
0    2  related-1;request-0;offer-0;aid_related-0;medi...
1    7  related-1;request-0;offer-0;aid_related-1;medi...
2    8  related-1;request-0;offer-0;aid_related-0;medi...
3    9  related-1;request-1;offer-0;aid_related-1;medi...
4   12  related-1;request-0;offer-0;aid_related-0;medi...
5   14  related-0;request-0;offer-0;aid_related-0;medi...
6   15  related-1;request-0;offer-0;aid_related-0;medi...
7   16  related-1;request-1;offer-0;aid_related-1;medi...
8   17  related-0;request-0;offer-0;aid_related-0;medi...
9   18  related-1;request-1;offer-0;aid_related-1;medi...
10  20  related-1;request-1;offer-0;aid_related-1;medi...
11  21  related-0;request-0;offer-0;aid_related-0;medi...
12  22  related-1;request-1;offer-0;aid_related-1;medi...
13  24  related-1;request-1;offer-0;aid_related-1;medi...
14  25  related-1;request-0;offer-0;aid_related-0;medi...
15  26  related-1;request-1;offer-0;aid_related-1;medi...
16  27  related-1;request-1;offer-0;aid_related-1;medi...
17  28  related-0;request-0;offer-0;aid_related-0;medi...
18  30  related-0;request-0;offer-0;aid_related-0;medi...
19  31  related-1;request-0;offer-0;aid_related-0;medi...
20  32  related-1;request-0;offer-0;aid_related-0;medi...
21  33  related-1;request-1;offer-0;aid_related-1;medi...
22  34  related-1;request-1;offer-0;aid_related-1;medi...
23  35  related-1;request-1;offer-0;aid_related-1;medi...
24  36  related-1;request-0;offer-0;aid_related-0;medi...
25  37  related-0;request-0;offer-0;aid_related-0;medi...
26  38  related-1;request-1;offer-0;aid_related-1;medi...
27  39  related-1;request-1;offer-0;aid_related-1;medi...
28  41  related-1;request-1;offer-0;aid_related-1;medi...
29  42  related-1;request-1;offer-0;aid_related-1;medi...

In [5]:
messages['id'].nunique()

26180

In [6]:
categories['id'].nunique()

26180

In [7]:
#number of rows and columns of categories  data
print('Categories dataset has', categories.shape[0],'rows/message and', categories.shape[1], 'columns/features')

Categories dataset has 26248 rows/message and 2 columns/features

### 2. Merge datasets.
- Merge the messages and categories datasets using the common id
- Assign this combined dataset to `df`, which will be cleaned in the following steps

In [8]:
# merge datasets
df = pd.merge(messages, categories, how='inner', on='id') #passing inner to how parameter keeps keeps rows where the 'id' exists in both dataframes.
df.head(10)

,id,message,original,genre,categories
0,2,Weather update - a cold front from Cuba that c...,Un front froid se retrouve sur Cuba ce matin. ...,direct,related-1;request-0;offer-0;aid_related-0;medi...
1,7,Is the Hurricane over or is it not over,Cyclone nan fini osinon li pa fini,direct,related-1;request-0;offer-0;aid_related-1;medi...
2,8,Looking for someone but no name,"Patnm, di Maryani relem pou li banm nouvel li ...",direct,related-1;request-0;offer-0;aid_related-0;medi...
3,9,UN reports Leogane 80-90 destroyed. Only Hospi...,UN reports Leogane 80-90 destroyed. Only Hospi...,direct,related-1;request-1;offer-0;aid_related-1;medi...
4,12,"says: west side of Haiti, rest of the country ...",facade ouest d Haiti et le reste du pays aujou...,direct,related-1;request-0;offer-0;aid_related-0;medi...
5,14,Information about the National Palace-,Informtion au nivaux palais nationl,direct,related-0;request-0;offer-0;aid_related-0;medi...
6,15,Storm at sacred heart of jesus,Cyclone Coeur sacr de jesus,direct,related-1;request-0;offer-0;aid_related-0;medi...
7,16,"Please, we need tents and water. We are in Sil...",Tanpri nou bezwen tant avek dlo nou zon silo m...,direct,related-1;request-1;offer-0;aid_related-1;medi...
8,17,"I would like to receive the messages, thank you",Mwen ta renmen jouin messag yo. Merci,direct,related-0;request-0;offer-0;aid_related-0;medi...
9,18,I am in Croix-des-Bouquets. We have health iss...,"Nou kwadebouke, nou gen pwoblem sant m yo nan ...",direct,related-1;request-1;offer-0;aid_related-1;medi...

In [9]:
df.shape

(26386, 5)

### 3. Split `categories` into separate category columns.
- Split the values in the `categories` column on the `;` character so that each value becomes a separate column. You'll find [this method](https://pandas.pydata.org/pandas-docs/version/0.23/generated/pandas.Series.str.split.html) very helpful! Make sure to set `expand=True`.
- Use the first row of categories dataframe to create column names for the categories data.
- Rename columns of `categories` with new column names.

In [10]:
# create a dataframe of the 36 individual category columns
categories = categories['categories'].str.split(pat=';', expand=True)
categories.head()

,0,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
0,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
1,related-1,request-0,offer-0,aid_related-1,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-1,floods-0,storm-1,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
2,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
3,related-1,request-1,offer-0,aid_related-1,medical_help-0,medical_products-1,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
4,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0

In [11]:
# select the first row of the categories dataframe
row = categories.iloc[0]

# use this row to extract a list of new column names for categories.
# one way is to apply a lambda function that takes everything 
# up to the second to last character of each string with slicing
category_colnames = collist = list(map(lambda i: i[ : -2], row)) 
print(category_colnames)

['related', 'request', 'offer', 'aid_related', 'medical_help', 'medical_products', 'search_and_rescue', 'security', 'military', 'child_alone', 'water', 'food', 'shelter', 'clothing', 'money', 'missing_people', 'refugees', 'death', 'other_aid', 'infrastructure_related', 'transport', 'buildings', 'electricity', 'tools', 'hospitals', 'shops', 'aid_centers', 'other_infrastructure', 'weather_related', 'floods', 'storm', 'fire', 'earthquake', 'cold', 'other_weather', 'direct_report']

In [12]:
# rename the columns of `categories`
categories.columns = category_colnames
categories.head()

,related,request,offer,aid_related,medical_help,medical_products,search_and_rescue,security,military,child_alone,...,aid_centers,other_infrastructure,weather_related,floods,storm,fire,earthquake,cold,other_weather,direct_report
0,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
1,related-1,request-0,offer-0,aid_related-1,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-1,floods-0,storm-1,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
2,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
3,related-1,request-1,offer-0,aid_related-1,medical_help-0,medical_products-1,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
4,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0

### 4. Convert category values to just numbers 0 or 1.
- Iterate through the category columns in df to keep only the last character of each string (the 1 or 0). For example, `related-0` becomes `0`, `related-1` becomes `1`. Convert the string to a numeric value.
- You can perform [normal string actions on Pandas Series](https://pandas.pydata.org/pandas-docs/stable/text.html#indexing-with-str), like indexing, by including `.str` after the Series. You may need to first convert the Series to be of type string, which you can do with `astype(str)`.

In [13]:
for column in categories:
    # set each value to be the last character of the string
    categories[column] = categories[column].map(lambda x : x[-1] )
    
    # convert column from string to numeric
    categories[column] = categories[column].astype(int)
categories.head()

,related,request,offer,aid_related,medical_help,medical_products,search_and_rescue,security,military,child_alone,...,aid_centers,other_infrastructure,weather_related,floods,storm,fire,earthquake,cold,other_weather,direct_report
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,1,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,1,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### 5. Replace `categories` column in `df` with new category columns.
- Drop the categories column from the df dataframe since it is no longer needed.
- Concatenate df and categories data frames.

In [15]:
# drop the original categories column from `df`
df.drop(['categories'], axis=1, inplace=True)

df.head()

,id,message,original,genre
0,2,Weather update - a cold front from Cuba that c...,Un front froid se retrouve sur Cuba ce matin. ...,direct
1,7,Is the Hurricane over or is it not over,Cyclone nan fini osinon li pa fini,direct
2,8,Looking for someone but no name,"Patnm, di Maryani relem pou li banm nouvel li ...",direct
3,9,UN reports Leogane 80-90 destroyed. Only Hospi...,UN reports Leogane 80-90 destroyed. Only Hospi...,direct
4,12,"says: west side of Haiti, rest of the country ...",facade ouest d Haiti et le reste du pays aujou...,direct

In [16]:
# concatenate the original dataframe with the new `categories` dataframe
df = pd.concat([df, categories], axis=1)
df.head()

,id,message,original,genre,related,request,offer,aid_related,medical_help,medical_products,...,aid_centers,other_infrastructure,weather_related,floods,storm,fire,earthquake,cold,other_weather,direct_report
0,2,Weather update - a cold front from Cuba that c...,Un front froid se retrouve sur Cuba ce matin. ...,direct,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,7,Is the Hurricane over or is it not over,Cyclone nan fini osinon li pa fini,direct,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,8,Looking for someone but no name,"Patnm, di Maryani relem pou li banm nouvel li ...",direct,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,9,UN reports Leogane 80-90 destroyed. Only Hospi...,UN reports Leogane 80-90 destroyed. Only Hospi...,direct,1.0,1.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,12,"says: west side of Haiti, rest of the country ...",facade ouest d Haiti et le reste du pays aujou...,direct,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### 6. Remove duplicates.
- Check how many duplicates are in this dataset.
- Drop the duplicates.
- Confirm duplicates were removed.

In [17]:
# check number of duplicates
df.duplicated().sum()

41

In [18]:
# drop duplicates
df.drop_duplicates(inplace=True)

In [19]:
# check number of duplicates
df.duplicated().sum()

0

In [20]:
df.isnull().sum()

id                            0
message                       0
original                  16122
genre                         0
related                     138
request                     138
offer                       138
aid_related                 138
medical_help                138
medical_products            138
search_and_rescue           138
security                    138
military                    138
child_alone                 138
water                       138
food                        138
shelter                     138
clothing                    138
money                       138
missing_people              138
refugees                    138
death                       138
other_aid                   138
infrastructure_related      138
transport                   138
buildings                   138
electricity                 138
tools                       138
hospitals                   138
shops                       138
aid_centers                 138
other_infrastructure        138
weather_related             138
floods                      138
storm                       138
fire                        138
earthquake                  138
cold                        138
other_weather               138
direct_report               138
dtype: int64

In [21]:
df.dropna(inplace=True)

In [22]:
df.isnull().sum()

id                        0
message                   0
original                  0
genre                     0
related                   0
request                   0
offer                     0
aid_related               0
medical_help              0
medical_products          0
search_and_rescue         0
security                  0
military                  0
child_alone               0
water                     0
food                      0
shelter                   0
clothing                  0
money                     0
missing_people            0
refugees                  0
death                     0
other_aid                 0
infrastructure_related    0
transport                 0
buildings                 0
electricity               0
tools                     0
hospitals                 0
shops                     0
aid_centers               0
other_infrastructure      0
weather_related           0
floods                    0
storm                     0
fire                      0
earthquake                0
cold                      0
other_weather             0
direct_report             0
dtype: int64

In [30]:
df.shape

(10223, 40)

In [27]:
#Check if There is value 2 in dataset

if 2 in df.values:
    print(df.columns[df.isin([2]).any()]) #Print the column that contains 2
else:
    print('This values does not exist')

Index(['id', 'related'], dtype='object')

In [28]:
#print the rows that have the value 2 
df.loc[df['related']==2,:]

,id,message,original,genre,related,request,offer,aid_related,medical_help,medical_products,...,aid_centers,other_infrastructure,weather_related,floods,storm,fire,earthquake,cold,other_weather,direct_report
117,146,Dans la zone de Saint Etienne la route de Jacm...,Nan zon st. etine rout jakmel la bloke se mize...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
219,261,"Hygienic . .. , mobile toilets, batteries, gen...","ERS HYGIENIQUES, TOILETTES MOBILES, BATTERIES,...",direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
305,371,I am a surviver of the earthkaque see how you ...,Mwen se yon viktim nan katastrf ki sot pase a ...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
460,563,I am located in Route Freres- Impasse Fortin. ...,mou sou route fr impasse fortin pi wo maket gr...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
576,698,"Please people in Carrefour, Magloire Ambroide ...","Sil te ple moun nan kafou fy, avni maglwa ambw...",direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
655,801,"People in grand goave, especially n Foch. we a...",Mou nan depatman lwes zone gran gwave localite...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
656,802,A lot of victims arrive at the hospital Erez M...,Gen yon bann viktim ki rive nan lopital Kl Ere...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
883,1056,oh please we are in the need of food. water. w...,tanpri souple nou nan necesite manje. Dlo. Kot...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
897,1074,And where will I make contact with you? Thank ...,epi ki kote m ja pran kontak ak nou. Mesi,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
925,1106,I do not have a card for me to call my family,MWEN PAGEN KAT POU MWEN RELE FANMI MWEN,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
931,1113,we sleep with the baby. Thanks in advance for ...,sa nou demi avek ti bebe. Mesi davans pou d no...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
933,1117,We are living in deplorable conditions. We are...,REES ET NOUS SOMMES DANS UNE SITUATION TRES EP...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1228,1453,"I'm in/at Kot Plaj ( beach ) 22#120, my house ...","Mwen nan kot plaj 22#120, kay mwen kraze, mwen...",direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1250,1477,Carefour Feiulles zone Savane Pistache. we hav...,k foufey nan zone savann pistache pa janm jwen...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1311,1544,I would like to know if it's true that there i...,Jaimerais savoir si cest vrai il va y avoir un...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1403,1642,I would like some information on the earthquake.,Un peut d. information sur le trenblement de t...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1498,1738,"Please, do something for us, we are among near...","Tanpri souple fe yon bagay pou nou, nou nan sa...",direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1686,1943,"This family need water and food, the child is ...",My name is resignac jean auberdson. i live at ...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1780,2042,? they are sleeping in the street. They need,"nt, yap demi nan lari yo bezwen.",direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2344,2685,The people in Henfrasa across from the La Paix...,Mou nan enfrasa enfas lopital lape yo bezwen m...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2469,2825,How many US soldiers in Haiti?,KONBYEN SOLDA AMERIKEN KI AN AYITI,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2534,2908,We are hungry and thirst. ?first merger ? firs...,Nous avons faim et soif mrger premire route s...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2550,2926,what is being done so that we stop sleeping in...,Kisa k ap fet pou nou sispann demi nan lari a....,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3019,3465,We are inhabitants of 4th Avenue in Bolosse. W...,Nou se abitan nan 4me avni bolos nou pa janm r...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3124,3587,"I am living really badly. I can't eat, I have ...",ap mal viv. mwen paka manje mwen pa gen kote p...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3360,3852,I would like to give blood but I'm all the way...,mwen ta renmen bay san men mwen jis gro- m n,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3614,4128,hallo if you're still alive consider that you'...,Salut! Si wap viv toujou konsidere w kom yon n...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4587,5196,If they don't give me a card and food has been...,Si yo pa bam kat e ke manje distribye nan zon ...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4629,5240,"Please, we don't have tents to sleep. We are b...",prela tank pounou demi mesi anpil noubmache le...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4630,5241,We are in Leogane. We have sheltered in a dese...,se leogan mwenye mwen pajanm anyen ditou ditou...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12237,14139,when it will likely to be implemented,IS PAR AMAL KAB KARNE KA IMKAN HAI),direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12238,14140,When you think is the possibility to work on this,IS PAR AMAL KAB KARNE KA IMKAN HAI,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12241,14156,Tahsel. jamur. Rajanpur?,tahsel. jamur. d.s.s. a,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12248,14186,KHALIL AHMAD ARIAN KOTLA MUGHLAN TAHSEL JAMPUR...,KHALIL AHMAD ARIAN KOTLA MUGHLAN. TAHSIL JAMPU...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12258,14226,Aijaz ahmed dit khairpur meirs thahsel nara vl...,a,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12265,14239,IT IS MY HUMBLE REQUEST THAT WE DO NOT RECIEVE...,mera arz hai k hamen abi tak watan card nahi m...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12269,14244,my house broken down due to floods.it cannot b...,Mera ghar selab ki waja sy gir giya hy. aur do...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12273,14246,Mera ghar selab ki waja sy gir giya hy. aur do...,a. a. a. ...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12283,14289,AURANG ZEB S/O GULAB DIN DIST MIANWALI TEH ESS...,AURANG ZEB S/O GULAB DIN DIST MIANWALI TEH ESS...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12288,14302,Min basti Hamed PUR tehsil and district Rahim ...,SE TALUQ RAKHTA 3 a,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12290,14305,BBC HELP LINE K TUFAIL MIN TEH.JAMPUR DISTT.RA...,a tufail jampur rajanpur ' ...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12291,14308,I belong to basti hamed PUR tehsil and distric...,Min basti hamed PUR tehsil and district RAHIM ...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12292,14309,Min basti hamed PUR tehsil and district RAHIM ...,Min basti hamed PUR tehsil and district RAHIM ...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12293,14315,,a,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12296,14323,"most affected areas in Punjab kot addu, jampur...",a,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12299,14336,"They are not giving us ration, only giving to ...",Mouladad Bajkani village Abdul Majeed Bajkani ...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12306,14358,How will i know the answer? Please explain. Th...,Mujhi Jawab ka pata kaisi lagi gha. Krupaya Sa...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12314,14391,"Dadu still needs food, medicines, cloths, metr...","Dadu ko abhi bhi khana, dawai, kapde, takiye a...",direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12316,14393,Dear Sir There has been great flood in our are...,Dear sir humaray alakay main bahut sailaab aya...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12317,14404,NEED FOOD AND MEDICAL AID IN SAIDU SHARIF SWAT,Khdya aura SAIDU arpha sva m cikits sahyat ki ...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12318,14405,Disease assessment needed in Dadu,a,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12322,14409,new flood in jaffar abad after damaged Tori band.,Katigrasta tr baia ke bda jaffarabad m nay bha.,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12323,14410,new flood in jaffar abad after damaged Tori band,silab jaffar abad ponoch gya ha tori band ko n...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12324,14411,new flood in jaffarabad after damaged Tori dam.,Tori Band ke tootne ke baad Jaffarabad mein na...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12333,14440,PIDE survey says Pakistan is recovering well w...,PIDE survey kehta hai ki Pakistan mein flood k...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12342,14468,Flood victims crying in cool. no shelter avail...,Bha pite nta m r. K' raya haa m upalabdha hai....,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12344,14474,PLEASE SEND ME VERIFICATION CODE,.,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12351,14488,from dera allah yar cityNadra ne 13 aug2010 tk...,DERA ALLAH YAR SHAHAR SE NADRA NE TERAH AGAST ...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12353,14494,request investigation on Food delivery,a,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12405,14611,tibba chandia teh.Jam pur Dist.Rajan pur Help ...,tibba chandia teh.Jam pur Dist.Rajan pur Help ...,direct,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [31]:
#Drop the rows that have value 2
df.drop(df[df['related'] == 2].index, inplace = True)

In [32]:
df.shape

(10094, 40)

### 7. Save the clean dataset into an sqlite database.
You can do this with pandas [`to_sql` method](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_sql.html) combined with the SQLAlchemy library. Remember to import SQLAlchemy's `create_engine` in the first cell of this notebook to use it below.

In [33]:
engine = create_engine('sqlite:///InsertDatabaseName.db')
df.to_sql('InsertTableName', engine, index=False)

### 8. Use this notebook to complete `etl_pipeline.py`
Use the template file attached in the Resources folder to write a script that runs the steps above to create a database based on new datasets specified by the user. Alternatively, you can complete `etl_pipeline.py` in the classroom on the `Project Workspace IDE` coming later.